### ISSUE TITLE
EmuDeck Compression Tool - Wii/GameCube

### ISSUE THREAD

**Issue by F9Alejandro** [EmuDeck/emudeck-electron#10]
**Describe the bug**
Tool scans all directories except for wii and GameCube.

**To Reproduce**
1. EmuDeck Compression Tool
2. Click on 'Run the Compression Tool'
3. Click on 'Ok, let\'s start'

**Expected behavior**
Compress Wii and GameCube .iso files to RVZ

**SteamDeck stable desktop mode**

**Additional context**

**Comment by Godsbane** [comment]
Thanks, this is fixed in beta, and being tracked in the main emudeck GitHub already :)
