### ISSUE TITLE
Add ability to export steam entries

### ISSUE THREAD

**Issue by maddox** [EmuDeck/emudeck-electron#12]
I know this is more an issue for Steam Rom Manager, but you guys do a lot of work on it, and this is sort of in line with EmuDeck.

It would be awesome if there was a way to export the work done in Steam Rom Manager, to use on another computer.

Since using the Steam Deck and setting up ChimeraOS on a gaming rig, I'm finding that I'm doing a lot of double work with Steam entries. I actually have 2 gaming PCs I keep in sync with emulation, so it's technically 3. It's actually 2x this work, because I have 2 profiles on each setup, one for me and one for my kid. So it's pretty monotonous and brutal 🤣 

It would be awesome if there was some way to take the work done in one place, and have the ability to export to another setup, so that it's a quick easy import of all entries and art.

**Comment by Godsbane** [comment]
while i haven't used it - there is an export option now, after you preview. it's a relatively new feature. maybe it suits your needs?

![image](https://user-images.githubusercontent.com/1683513/235283378-e0c6b295-efd7-40a4-93ad-9457c6c82655.png)

**Comment by maddox** [comment]
🤦‍♂️ I'm sitting here playing with the new version, inspecting everything, and lamenting on having to do this stuff twice, and I somehow missed this. Good lord, heh. Thanks, this is hugely helpful! I'll give it a try.

**Comment by maddox** [comment]
Ok, this looks exactly like what I'm looking for. It looks like it even exports images picked directly in Steam via the SteamGridDB plugin. And I can make any kind of changes via the JSON if I need to.

Thanks 🤦‍♂️

**Comment by Godsbane** [comment]
happy to help
