### ISSUE TITLE
Consider a Desktop/Handheld Setting in Setup

### ISSUE THREAD

**Issue by maddox** [EmuDeck/emudeck-electron#13]
EmuDeck came from, and continues to be for the Steam Deck, and this has obviously been great. But a lot of us are using it on Linux systems like, ChimeraOS, where we can run our emulators at 4K.

It would be great to have a way to set that we want 4K configurations, and resolutions would be set to 4K on emulators, rather than 720p. Right now, after running EmuDeck, we have to go into each emulator and retroarch core settings (PSX, Dreamcast), to adjust the resolutions things run at. 

This isn't *that* bad, but it sure would be one less thing to have do, especially if you're adopting big new EmuDeck configuration changes often.

**Comment by dragoonDorise** [comment]
Hi! @maddox , we already have that implemented on Windows, doing it on Linux is trivial for us but we need to add proper Linux support for other distros, it's on our plans so don't worry :)

**Comment by maddox** [comment]
Woo!

**Comment by dragoonDorise** [comment]
@Maddox I did this some weeks ago and I completely forgot :/. It's available when selecting ChimeraOS + custom mode
